### ISSUE TITLE
Switch Version keeps crashing

### ISSUE THREAD

**Issue by djbolas** [Torphedo/BOTW-ModdingGuide#2]
I'm using the Switch version and it keeps crashing when I get to Laparoh Mesa in the Gerudo Highlands to fight the Custom Black and Gold Lynel.

**Comment by Torphedo** [comment]
Put this on the [Second Wind GitHub](https://github.com/Nitr4m12/Second-Wind-Switch/issues), this repo just hosts the guide and nothing else
